// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfbJdJg6LqwFdRQlbrnO3UYhV6OGC1yJc',
    appId: '1:73177864699:web:279e2024e06ff760c9535e',
    messagingSenderId: '73177864699',
    projectId: 'outs-9aeb2',
    authDomain: 'outs-9aeb2.firebaseapp.com',
    storageBucket: 'outs-9aeb2.appspot.com',
    measurementId: 'G-LVXRTWJWHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfbJdJg6LqwFdRQlbrnO3UYhV6OGC1yJc',
    appId: '1:73177864699:android:0a78f2df515d81d8c9535e',
    messagingSenderId: '73177864699',
    projectId: 'outs-9aeb2',
    storageBucket: 'outs-9aeb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfbJdJg6LqwFdRQlbrnO3UYhV6OGC1yJc',
    appId: '1:73177864699:ios:e606703368c67394c9535e',
    messagingSenderId: '73177864699',
    projectId: 'outs-9aeb2',
    storageBucket: 'outs-9aeb2.appspot.com',
    iosClientId:
        '73177864699-r65337hstimifqqqn2j8f9r6d7eb77v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.outsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfbJdJg6LqwFdRQlbrnO3UYhV6OGC1yJc',
    appId: '1:73177864699:ios:e606703368c67394c9535e',
    messagingSenderId: '73177864699',
    projectId: 'outs-9aeb2',
    storageBucket: 'outs-9aeb2.appspot.com',
    iosClientId:
        '73177864699-r65337hstimifqqqn2j8f9r6d7eb77v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.outsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfbJdJg6LqwFdRQlbrnO3UYhV6OGC1yJc',
    appId: '1:73177864699:web:81dc36aca3b0a00dc9535e',
    messagingSenderId: '73177864699',
    projectId: 'outs-9aeb2',
    authDomain: 'outs-9aeb2.firebaseapp.com',
    storageBucket: 'outs-9aeb2.appspot.com',
    measurementId: 'G-65NZE66BKS',
  );
}
