# Definisce il target minimo di iOS
platform :ios, '13.0'

# Indica di usare framework dinamici
use_frameworks!
use_modular_headers!

target 'Runner' do
  # Includi tutte le dipendenze di Flutter automaticamente
  flutter_install_ios_engine_pod File.dirname(File.realpath(__FILE__))
  flutter_install_ios_plugin_pods File.dirname(File.realpath(__FILE__))

  # Dipendenze di Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'

  # Google Maps (se necessario)
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods per testing
  end
end
